### ISSUE TITLE
Guzzle compatibility

### ISSUE THREAD

**Issue by gfernandez-me** [LacunaSoftware/RestPkiPhpClient#1]
Hello,
In some way to make it work with
"guzzlehttp/guzzle": "^7.0.1",

I'm using Laravel 8 and I noticed that your lib is incompatible with the new libraries.

**Comment by MimyS** [comment]
Hi,
Thank you for reporting.
We updated the guzzle version and the restpki-client versions above 2.9.1 work with Laravel 8.
